version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=${MAX_HEAP_SIZE}
      - HEAP_NEWSIZE=${HEAP_NEWSIZE}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - cassandra_home:/home
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra


  cassandra-web:
    image: delermando/docker-cassandra-web:v0.4.0
    platform: linux/amd64
    profiles : 
      - web
    container_name: cassandra_web
    ports:
      - 3000:3000
    environment:
      - CASSANDRA_HOST_IP=${CASSANDRA_HOST_IP}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
    depends_on:
      - cassandra
    networks:
      - cassandra


volumes:
  cassandra_data:
    name: cassandra_data
  cassandra_home:
    name: cassandra_data


networks:
  cassandra:
    driver: bridge
    name: cassandra_network